server:
  port : 8081
spring:
  application:
    name: ljselectiontarifas
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:./ljselectiontarifas
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:/db/migration/H2
    schemas: ljselectiontarifas
logging:
  level:
    root: INFO
    com:
      ljselection: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
            
feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic
